package com.touchnvoteui.generictype;

import android.widget.CheckBox;
import android.widget.RadioButton;
import android.widget.TextView;

public class var {

	public static TextView  question1;
	public static TextView  question2;
	public static TextView  question3;
	public static TextView  question4;
	public static TextView  question5;
	public static TextView  question6;
	public static TextView  question7;
	public static TextView  question8;
	public static TextView  question9;
	public static TextView  question10;
	
	public static RadioButton radio1_1;
	public static RadioButton radio1_2;
	public static RadioButton radio1_3;
	public static RadioButton radio1_4;
	public static RadioButton radio2_1;
	public static RadioButton radio2_2;
	public static RadioButton radio2_3;
	public static RadioButton radio2_4;
	public static RadioButton radio3_1;
	public static RadioButton radio3_2;
	public static RadioButton radio3_3;
	public static RadioButton radio3_4;
	public static RadioButton radio4_1;
	public static RadioButton radio4_2;
	public static RadioButton radio4_3;
	public static RadioButton radio4_4;
	public static RadioButton radio5_1;
	public static RadioButton radio5_2;
	public static RadioButton radio5_3;
	public static RadioButton radio5_4;
	public static RadioButton radio6_1;
	public static RadioButton radio6_2;
	public static RadioButton radio6_3;
	public static RadioButton radio6_4;
	public static RadioButton radio7_1;
	public static RadioButton radio7_2;
	public static RadioButton radio7_3;
	public static RadioButton radio7_4;
	public static RadioButton radio8_1;
	public static RadioButton radio8_2;
	public static RadioButton radio8_3;
	public static RadioButton radio8_4;
	public static RadioButton radio9_1;
	public static RadioButton radio9_2;
	public static RadioButton radio9_3;
	public static RadioButton radio9_4;
	public static RadioButton radio10_1;
	public static RadioButton radio10_2;
	public static RadioButton radio10_3;
	public static RadioButton radio10_4;
	
	public static CheckBox combo1_1;
	public static CheckBox combo1_2;
	public static CheckBox combo1_3;
	public static CheckBox combo1_4;
	public static CheckBox combo2_1;
	public static CheckBox combo2_2;
	public static CheckBox combo2_3;
	public static CheckBox combo2_4;
	public static CheckBox combo3_1;
	public static CheckBox combo3_2;
	public static CheckBox combo3_3;
	public static CheckBox combo3_4;
	public static CheckBox combo4_1;
	public static CheckBox combo4_2;
	public static CheckBox combo4_3;
	public static CheckBox combo4_4;
	public static CheckBox combo5_1;
	public static CheckBox combo5_2;
	public static CheckBox combo5_3;
	public static CheckBox combo5_4;
	public static CheckBox combo6_1;
	public static CheckBox combo6_2;
	public static CheckBox combo6_3;
	public static CheckBox combo6_4;
	public static CheckBox combo7_1;
	public static CheckBox combo7_2;
	public static CheckBox combo7_3;
	public static CheckBox combo7_4;
	public static CheckBox combo8_1;
	public static CheckBox combo8_2;
	public static CheckBox combo8_3;
	public static CheckBox combo8_4;
	public static CheckBox combo9_1;
	public static CheckBox combo9_2;
	public static CheckBox combo9_3;
	public static CheckBox combo9_4;
	public static CheckBox combo10_1;
	public static CheckBox combo10_2;
	public static CheckBox combo10_3;
	public static CheckBox combo10_4;
	
}
