/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-11-22 19:59:01 UTC)
 * on 2013-11-27 at 07:09:07 UTC 
 * Modify at your own risk.
 */

package com.touchnvoteui.entities.userdetailsendpoint;

/**
 * Service definition for Userdetailsendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link UserdetailsendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Userdetailsendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the userdetailsendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://touchnvote.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "userdetailsendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Userdetailsendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Userdetailsendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getUserDetails".
   *
   * This request holds the parameters needed by the the userdetailsendpoint server.  After setting
   * any optional parameters, call the {@link GetUserDetails#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetUserDetails getUserDetails(java.lang.Long id) throws java.io.IOException {
    GetUserDetails result = new GetUserDetails(id);
    initialize(result);
    return result;
  }

  public class GetUserDetails extends UserdetailsendpointRequest<com.touchnvoteui.entities.userdetailsendpoint.model.UserDetails> {

    private static final String REST_PATH = "userdetails/{id}";

    /**
     * Create a request for the method "getUserDetails".
     *
     * This request holds the parameters needed by the the userdetailsendpoint server.  After setting
     * any optional parameters, call the {@link GetUserDetails#execute()} method to invoke the remote
     * operation. <p> {@link GetUserDetails#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetUserDetails(java.lang.Long id) {
      super(Userdetailsendpoint.this, "GET", REST_PATH, null, com.touchnvoteui.entities.userdetailsendpoint.model.UserDetails.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetUserDetails setAlt(java.lang.String alt) {
      return (GetUserDetails) super.setAlt(alt);
    }

    @Override
    public GetUserDetails setFields(java.lang.String fields) {
      return (GetUserDetails) super.setFields(fields);
    }

    @Override
    public GetUserDetails setKey(java.lang.String key) {
      return (GetUserDetails) super.setKey(key);
    }

    @Override
    public GetUserDetails setOauthToken(java.lang.String oauthToken) {
      return (GetUserDetails) super.setOauthToken(oauthToken);
    }

    @Override
    public GetUserDetails setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetUserDetails) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetUserDetails setQuotaUser(java.lang.String quotaUser) {
      return (GetUserDetails) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetUserDetails setUserIp(java.lang.String userIp) {
      return (GetUserDetails) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetUserDetails setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetUserDetails set(String parameterName, Object value) {
      return (GetUserDetails) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertUserDetails".
   *
   * This request holds the parameters needed by the the userdetailsendpoint server.  After setting
   * any optional parameters, call the {@link InsertUserDetails#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.touchnvoteui.entities.userdetailsendpoint.model.UserDetails}
   * @return the request
   */
  public InsertUserDetails insertUserDetails(com.touchnvoteui.entities.userdetailsendpoint.model.UserDetails content) throws java.io.IOException {
    InsertUserDetails result = new InsertUserDetails(content);
    initialize(result);
    return result;
  }

  public class InsertUserDetails extends UserdetailsendpointRequest<com.touchnvoteui.entities.userdetailsendpoint.model.UserDetails> {

    private static final String REST_PATH = "userdetails";

    /**
     * Create a request for the method "insertUserDetails".
     *
     * This request holds the parameters needed by the the userdetailsendpoint server.  After setting
     * any optional parameters, call the {@link InsertUserDetails#execute()} method to invoke the
     * remote operation. <p> {@link InsertUserDetails#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.touchnvoteui.entities.userdetailsendpoint.model.UserDetails}
     * @since 1.13
     */
    protected InsertUserDetails(com.touchnvoteui.entities.userdetailsendpoint.model.UserDetails content) {
      super(Userdetailsendpoint.this, "POST", REST_PATH, content, com.touchnvoteui.entities.userdetailsendpoint.model.UserDetails.class);
    }

    @Override
    public InsertUserDetails setAlt(java.lang.String alt) {
      return (InsertUserDetails) super.setAlt(alt);
    }

    @Override
    public InsertUserDetails setFields(java.lang.String fields) {
      return (InsertUserDetails) super.setFields(fields);
    }

    @Override
    public InsertUserDetails setKey(java.lang.String key) {
      return (InsertUserDetails) super.setKey(key);
    }

    @Override
    public InsertUserDetails setOauthToken(java.lang.String oauthToken) {
      return (InsertUserDetails) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertUserDetails setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertUserDetails) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertUserDetails setQuotaUser(java.lang.String quotaUser) {
      return (InsertUserDetails) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertUserDetails setUserIp(java.lang.String userIp) {
      return (InsertUserDetails) super.setUserIp(userIp);
    }

    @Override
    public InsertUserDetails set(String parameterName, Object value) {
      return (InsertUserDetails) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listUserDetails".
   *
   * This request holds the parameters needed by the the userdetailsendpoint server.  After setting
   * any optional parameters, call the {@link ListUserDetails#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListUserDetails listUserDetails() throws java.io.IOException {
    ListUserDetails result = new ListUserDetails();
    initialize(result);
    return result;
  }

  public class ListUserDetails extends UserdetailsendpointRequest<com.touchnvoteui.entities.userdetailsendpoint.model.CollectionResponseUserDetails> {

    private static final String REST_PATH = "userdetails";

    /**
     * Create a request for the method "listUserDetails".
     *
     * This request holds the parameters needed by the the userdetailsendpoint server.  After setting
     * any optional parameters, call the {@link ListUserDetails#execute()} method to invoke the remote
     * operation. <p> {@link ListUserDetails#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListUserDetails() {
      super(Userdetailsendpoint.this, "GET", REST_PATH, null, com.touchnvoteui.entities.userdetailsendpoint.model.CollectionResponseUserDetails.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListUserDetails setAlt(java.lang.String alt) {
      return (ListUserDetails) super.setAlt(alt);
    }

    @Override
    public ListUserDetails setFields(java.lang.String fields) {
      return (ListUserDetails) super.setFields(fields);
    }

    @Override
    public ListUserDetails setKey(java.lang.String key) {
      return (ListUserDetails) super.setKey(key);
    }

    @Override
    public ListUserDetails setOauthToken(java.lang.String oauthToken) {
      return (ListUserDetails) super.setOauthToken(oauthToken);
    }

    @Override
    public ListUserDetails setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListUserDetails) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListUserDetails setQuotaUser(java.lang.String quotaUser) {
      return (ListUserDetails) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListUserDetails setUserIp(java.lang.String userIp) {
      return (ListUserDetails) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListUserDetails setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListUserDetails setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListUserDetails set(String parameterName, Object value) {
      return (ListUserDetails) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeUserDetails".
   *
   * This request holds the parameters needed by the the userdetailsendpoint server.  After setting
   * any optional parameters, call the {@link RemoveUserDetails#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveUserDetails removeUserDetails(java.lang.Long id) throws java.io.IOException {
    RemoveUserDetails result = new RemoveUserDetails(id);
    initialize(result);
    return result;
  }

  public class RemoveUserDetails extends UserdetailsendpointRequest<Void> {

    private static final String REST_PATH = "userdetails/{id}";

    /**
     * Create a request for the method "removeUserDetails".
     *
     * This request holds the parameters needed by the the userdetailsendpoint server.  After setting
     * any optional parameters, call the {@link RemoveUserDetails#execute()} method to invoke the
     * remote operation. <p> {@link RemoveUserDetails#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveUserDetails(java.lang.Long id) {
      super(Userdetailsendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveUserDetails setAlt(java.lang.String alt) {
      return (RemoveUserDetails) super.setAlt(alt);
    }

    @Override
    public RemoveUserDetails setFields(java.lang.String fields) {
      return (RemoveUserDetails) super.setFields(fields);
    }

    @Override
    public RemoveUserDetails setKey(java.lang.String key) {
      return (RemoveUserDetails) super.setKey(key);
    }

    @Override
    public RemoveUserDetails setOauthToken(java.lang.String oauthToken) {
      return (RemoveUserDetails) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveUserDetails setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveUserDetails) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveUserDetails setQuotaUser(java.lang.String quotaUser) {
      return (RemoveUserDetails) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveUserDetails setUserIp(java.lang.String userIp) {
      return (RemoveUserDetails) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveUserDetails setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveUserDetails set(String parameterName, Object value) {
      return (RemoveUserDetails) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateUserDetails".
   *
   * This request holds the parameters needed by the the userdetailsendpoint server.  After setting
   * any optional parameters, call the {@link UpdateUserDetails#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.touchnvoteui.entities.userdetailsendpoint.model.UserDetails}
   * @return the request
   */
  public UpdateUserDetails updateUserDetails(com.touchnvoteui.entities.userdetailsendpoint.model.UserDetails content) throws java.io.IOException {
    UpdateUserDetails result = new UpdateUserDetails(content);
    initialize(result);
    return result;
  }

  public class UpdateUserDetails extends UserdetailsendpointRequest<com.touchnvoteui.entities.userdetailsendpoint.model.UserDetails> {

    private static final String REST_PATH = "userdetails";

    /**
     * Create a request for the method "updateUserDetails".
     *
     * This request holds the parameters needed by the the userdetailsendpoint server.  After setting
     * any optional parameters, call the {@link UpdateUserDetails#execute()} method to invoke the
     * remote operation. <p> {@link UpdateUserDetails#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.touchnvoteui.entities.userdetailsendpoint.model.UserDetails}
     * @since 1.13
     */
    protected UpdateUserDetails(com.touchnvoteui.entities.userdetailsendpoint.model.UserDetails content) {
      super(Userdetailsendpoint.this, "PUT", REST_PATH, content, com.touchnvoteui.entities.userdetailsendpoint.model.UserDetails.class);
    }

    @Override
    public UpdateUserDetails setAlt(java.lang.String alt) {
      return (UpdateUserDetails) super.setAlt(alt);
    }

    @Override
    public UpdateUserDetails setFields(java.lang.String fields) {
      return (UpdateUserDetails) super.setFields(fields);
    }

    @Override
    public UpdateUserDetails setKey(java.lang.String key) {
      return (UpdateUserDetails) super.setKey(key);
    }

    @Override
    public UpdateUserDetails setOauthToken(java.lang.String oauthToken) {
      return (UpdateUserDetails) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateUserDetails setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateUserDetails) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateUserDetails setQuotaUser(java.lang.String quotaUser) {
      return (UpdateUserDetails) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateUserDetails setUserIp(java.lang.String userIp) {
      return (UpdateUserDetails) super.setUserIp(userIp);
    }

    @Override
    public UpdateUserDetails set(String parameterName, Object value) {
      return (UpdateUserDetails) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Userdetailsendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Userdetailsendpoint}. */
    @Override
    public Userdetailsendpoint build() {
      return new Userdetailsendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link UserdetailsendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setUserdetailsendpointRequestInitializer(
        UserdetailsendpointRequestInitializer userdetailsendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(userdetailsendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
