/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-11-22 19:59:01 UTC)
 * on 2013-11-27 at 07:09:13 UTC 
 * Modify at your own risk.
 */

package com.touchnvoteui.entities.securedloginendpoint;

/**
 * Service definition for Securedloginendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link SecuredloginendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Securedloginendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the securedloginendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://touchnvote.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "securedloginendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Securedloginendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Securedloginendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getSecuredLogin".
   *
   * This request holds the parameters needed by the the securedloginendpoint server.  After setting
   * any optional parameters, call the {@link GetSecuredLogin#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetSecuredLogin getSecuredLogin(java.lang.String id) throws java.io.IOException {
    GetSecuredLogin result = new GetSecuredLogin(id);
    initialize(result);
    return result;
  }

  public class GetSecuredLogin extends SecuredloginendpointRequest<com.touchnvoteui.entities.securedloginendpoint.model.SecuredLogin> {

    private static final String REST_PATH = "securedlogin/{id}";

    /**
     * Create a request for the method "getSecuredLogin".
     *
     * This request holds the parameters needed by the the securedloginendpoint server.  After setting
     * any optional parameters, call the {@link GetSecuredLogin#execute()} method to invoke the remote
     * operation. <p> {@link GetSecuredLogin#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetSecuredLogin(java.lang.String id) {
      super(Securedloginendpoint.this, "GET", REST_PATH, null, com.touchnvoteui.entities.securedloginendpoint.model.SecuredLogin.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetSecuredLogin setAlt(java.lang.String alt) {
      return (GetSecuredLogin) super.setAlt(alt);
    }

    @Override
    public GetSecuredLogin setFields(java.lang.String fields) {
      return (GetSecuredLogin) super.setFields(fields);
    }

    @Override
    public GetSecuredLogin setKey(java.lang.String key) {
      return (GetSecuredLogin) super.setKey(key);
    }

    @Override
    public GetSecuredLogin setOauthToken(java.lang.String oauthToken) {
      return (GetSecuredLogin) super.setOauthToken(oauthToken);
    }

    @Override
    public GetSecuredLogin setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetSecuredLogin) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetSecuredLogin setQuotaUser(java.lang.String quotaUser) {
      return (GetSecuredLogin) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetSecuredLogin setUserIp(java.lang.String userIp) {
      return (GetSecuredLogin) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetSecuredLogin setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetSecuredLogin set(String parameterName, Object value) {
      return (GetSecuredLogin) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertSecuredLogin".
   *
   * This request holds the parameters needed by the the securedloginendpoint server.  After setting
   * any optional parameters, call the {@link InsertSecuredLogin#execute()} method to invoke the
   * remote operation.
   *
   * @param content the {@link com.touchnvoteui.entities.securedloginendpoint.model.SecuredLogin}
   * @return the request
   */
  public InsertSecuredLogin insertSecuredLogin(com.touchnvoteui.entities.securedloginendpoint.model.SecuredLogin content) throws java.io.IOException {
    InsertSecuredLogin result = new InsertSecuredLogin(content);
    initialize(result);
    return result;
  }

  public class InsertSecuredLogin extends SecuredloginendpointRequest<com.touchnvoteui.entities.securedloginendpoint.model.SecuredLogin> {

    private static final String REST_PATH = "securedlogin";

    /**
     * Create a request for the method "insertSecuredLogin".
     *
     * This request holds the parameters needed by the the securedloginendpoint server.  After setting
     * any optional parameters, call the {@link InsertSecuredLogin#execute()} method to invoke the
     * remote operation. <p> {@link InsertSecuredLogin#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param content the {@link com.touchnvoteui.entities.securedloginendpoint.model.SecuredLogin}
     * @since 1.13
     */
    protected InsertSecuredLogin(com.touchnvoteui.entities.securedloginendpoint.model.SecuredLogin content) {
      super(Securedloginendpoint.this, "POST", REST_PATH, content, com.touchnvoteui.entities.securedloginendpoint.model.SecuredLogin.class);
    }

    @Override
    public InsertSecuredLogin setAlt(java.lang.String alt) {
      return (InsertSecuredLogin) super.setAlt(alt);
    }

    @Override
    public InsertSecuredLogin setFields(java.lang.String fields) {
      return (InsertSecuredLogin) super.setFields(fields);
    }

    @Override
    public InsertSecuredLogin setKey(java.lang.String key) {
      return (InsertSecuredLogin) super.setKey(key);
    }

    @Override
    public InsertSecuredLogin setOauthToken(java.lang.String oauthToken) {
      return (InsertSecuredLogin) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertSecuredLogin setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertSecuredLogin) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertSecuredLogin setQuotaUser(java.lang.String quotaUser) {
      return (InsertSecuredLogin) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertSecuredLogin setUserIp(java.lang.String userIp) {
      return (InsertSecuredLogin) super.setUserIp(userIp);
    }

    @Override
    public InsertSecuredLogin set(String parameterName, Object value) {
      return (InsertSecuredLogin) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listSecuredLogin".
   *
   * This request holds the parameters needed by the the securedloginendpoint server.  After setting
   * any optional parameters, call the {@link ListSecuredLogin#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListSecuredLogin listSecuredLogin() throws java.io.IOException {
    ListSecuredLogin result = new ListSecuredLogin();
    initialize(result);
    return result;
  }

  public class ListSecuredLogin extends SecuredloginendpointRequest<com.touchnvoteui.entities.securedloginendpoint.model.CollectionResponseSecuredLogin> {

    private static final String REST_PATH = "securedlogin";

    /**
     * Create a request for the method "listSecuredLogin".
     *
     * This request holds the parameters needed by the the securedloginendpoint server.  After setting
     * any optional parameters, call the {@link ListSecuredLogin#execute()} method to invoke the
     * remote operation. <p> {@link ListSecuredLogin#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListSecuredLogin() {
      super(Securedloginendpoint.this, "GET", REST_PATH, null, com.touchnvoteui.entities.securedloginendpoint.model.CollectionResponseSecuredLogin.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListSecuredLogin setAlt(java.lang.String alt) {
      return (ListSecuredLogin) super.setAlt(alt);
    }

    @Override
    public ListSecuredLogin setFields(java.lang.String fields) {
      return (ListSecuredLogin) super.setFields(fields);
    }

    @Override
    public ListSecuredLogin setKey(java.lang.String key) {
      return (ListSecuredLogin) super.setKey(key);
    }

    @Override
    public ListSecuredLogin setOauthToken(java.lang.String oauthToken) {
      return (ListSecuredLogin) super.setOauthToken(oauthToken);
    }

    @Override
    public ListSecuredLogin setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListSecuredLogin) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListSecuredLogin setQuotaUser(java.lang.String quotaUser) {
      return (ListSecuredLogin) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListSecuredLogin setUserIp(java.lang.String userIp) {
      return (ListSecuredLogin) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListSecuredLogin setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListSecuredLogin setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListSecuredLogin set(String parameterName, Object value) {
      return (ListSecuredLogin) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeSecuredLogin".
   *
   * This request holds the parameters needed by the the securedloginendpoint server.  After setting
   * any optional parameters, call the {@link RemoveSecuredLogin#execute()} method to invoke the
   * remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveSecuredLogin removeSecuredLogin(java.lang.String id) throws java.io.IOException {
    RemoveSecuredLogin result = new RemoveSecuredLogin(id);
    initialize(result);
    return result;
  }

  public class RemoveSecuredLogin extends SecuredloginendpointRequest<Void> {

    private static final String REST_PATH = "securedlogin/{id}";

    /**
     * Create a request for the method "removeSecuredLogin".
     *
     * This request holds the parameters needed by the the securedloginendpoint server.  After setting
     * any optional parameters, call the {@link RemoveSecuredLogin#execute()} method to invoke the
     * remote operation. <p> {@link RemoveSecuredLogin#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveSecuredLogin(java.lang.String id) {
      super(Securedloginendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveSecuredLogin setAlt(java.lang.String alt) {
      return (RemoveSecuredLogin) super.setAlt(alt);
    }

    @Override
    public RemoveSecuredLogin setFields(java.lang.String fields) {
      return (RemoveSecuredLogin) super.setFields(fields);
    }

    @Override
    public RemoveSecuredLogin setKey(java.lang.String key) {
      return (RemoveSecuredLogin) super.setKey(key);
    }

    @Override
    public RemoveSecuredLogin setOauthToken(java.lang.String oauthToken) {
      return (RemoveSecuredLogin) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveSecuredLogin setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveSecuredLogin) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveSecuredLogin setQuotaUser(java.lang.String quotaUser) {
      return (RemoveSecuredLogin) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveSecuredLogin setUserIp(java.lang.String userIp) {
      return (RemoveSecuredLogin) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveSecuredLogin setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveSecuredLogin set(String parameterName, Object value) {
      return (RemoveSecuredLogin) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateSecuredLogin".
   *
   * This request holds the parameters needed by the the securedloginendpoint server.  After setting
   * any optional parameters, call the {@link UpdateSecuredLogin#execute()} method to invoke the
   * remote operation.
   *
   * @param content the {@link com.touchnvoteui.entities.securedloginendpoint.model.SecuredLogin}
   * @return the request
   */
  public UpdateSecuredLogin updateSecuredLogin(com.touchnvoteui.entities.securedloginendpoint.model.SecuredLogin content) throws java.io.IOException {
    UpdateSecuredLogin result = new UpdateSecuredLogin(content);
    initialize(result);
    return result;
  }

  public class UpdateSecuredLogin extends SecuredloginendpointRequest<com.touchnvoteui.entities.securedloginendpoint.model.SecuredLogin> {

    private static final String REST_PATH = "securedlogin";

    /**
     * Create a request for the method "updateSecuredLogin".
     *
     * This request holds the parameters needed by the the securedloginendpoint server.  After setting
     * any optional parameters, call the {@link UpdateSecuredLogin#execute()} method to invoke the
     * remote operation. <p> {@link UpdateSecuredLogin#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param content the {@link com.touchnvoteui.entities.securedloginendpoint.model.SecuredLogin}
     * @since 1.13
     */
    protected UpdateSecuredLogin(com.touchnvoteui.entities.securedloginendpoint.model.SecuredLogin content) {
      super(Securedloginendpoint.this, "PUT", REST_PATH, content, com.touchnvoteui.entities.securedloginendpoint.model.SecuredLogin.class);
    }

    @Override
    public UpdateSecuredLogin setAlt(java.lang.String alt) {
      return (UpdateSecuredLogin) super.setAlt(alt);
    }

    @Override
    public UpdateSecuredLogin setFields(java.lang.String fields) {
      return (UpdateSecuredLogin) super.setFields(fields);
    }

    @Override
    public UpdateSecuredLogin setKey(java.lang.String key) {
      return (UpdateSecuredLogin) super.setKey(key);
    }

    @Override
    public UpdateSecuredLogin setOauthToken(java.lang.String oauthToken) {
      return (UpdateSecuredLogin) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateSecuredLogin setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateSecuredLogin) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateSecuredLogin setQuotaUser(java.lang.String quotaUser) {
      return (UpdateSecuredLogin) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateSecuredLogin setUserIp(java.lang.String userIp) {
      return (UpdateSecuredLogin) super.setUserIp(userIp);
    }

    @Override
    public UpdateSecuredLogin set(String parameterName, Object value) {
      return (UpdateSecuredLogin) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Securedloginendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Securedloginendpoint}. */
    @Override
    public Securedloginendpoint build() {
      return new Securedloginendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link SecuredloginendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setSecuredloginendpointRequestInitializer(
        SecuredloginendpointRequestInitializer securedloginendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(securedloginendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
